### PR TITLE
Add note about LogicalAssignmentPunctuator

### PR DESCRIPTION
**Pull request by jridgewell**
/to @rkirsling

### CODE REVIEW

**Comment by rkirsling** [comment]
Thanks! (Looks like some unrelated updates got roped in here though?)

**Comment by jridgewell** [comment]
My ecmarkup was outdated. Fixed.

**Comment by ljharb** [comment]
Perhaps it could be inlined here, since there’s ins tags?

**Comment by jridgewell** [comment]
ecmarkup strips the `<ins>` when it's inside a `one of` list. 😞

**Pull request merged**
